development:
  adapter: postgresql
  database: rebbin
  host: localhost
  username: root
  password: 

test:
  adapter: postgresql
  database: rebbin_test
  host: localhost
  username: root
  password:

production:
  adapter: postgresql
  database: rebbin_production
  host: localhost
  username: root
  password: 
